
const captionItem = "Lorem ipsum dolor sit amet"

export const dataSet = [

    {
      id:0,
      username:'shanbe mag',
      location:'Tehran,Iran',
      Thumbnail:require('../../assets/posts/Thumbnail-1.jpg'),
      image:require('../../assets/posts/1.jpg'),
      likes:101,
      comments: 8,
      caption: captionItem,
      likePost:false,
    },
    {
       id:1,
        username:'varzesh3',
        location:'paris,France',
        Thumbnail:require('../../assets/posts/Thumbnail-2.jpg'),
        image:require('../../assets/posts/2.jpg'),
        likes:7250,
        comments: 22,
        caption: captionItem,
        likePost:false,
      },
      {
        id:2,
        username:'tourism_iran',
        location:'Mazandaran',
        Thumbnail:require('../../assets/posts/Thumbnail-3.jpg'),
        image:require('../../assets/posts/3.jpg'),
        likes:1250,
        comments: 14,
        caption: captionItem,
        likePost:false,
      },
      {
        id:3,
        username:'dehgardi',
        location:'Kholin Darreh, Golestān, Iran',
        Thumbnail:require('../../assets/posts/Thumbnail-4.jpg'),
        image:require('../../assets/posts/4.jpg'),
        likes:1250,
        comments: 9,
        caption: captionItem,
        likePost:false,
      },
      {
        id:4,
        username:'nikodemus_s',
        location:'Sanfransisco',
        Thumbnail:require('../../assets/posts/Thumbnail-5.jpg'),
        image:require('../../assets/posts/5.jpg'),
        likes:89,
        comments: 5,
        caption: captionItem,
        likePost:false,
      },
];